name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infraestrutura Resiliente
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar sintaxe
        run: terraform validate

      - name: Formatar arquivos
        run: terraform fmt -check

      - name: Gerar plano
        run: terraform plan -var-file="terraform.tfvars"

      - name: Aplicar infraestrutura
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}